openapi: 3.0.3
info:
  title: New Spec - OpenAPI 3.0
  description: This is a sample description about this spec.
  termsOfService: ''
  contact:
    email: ''
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
externalDocs:
  description: Find out more about spec
  url: ''
servers:
  - url: https://mempool.space
    description: ''
tags:
  - name: Default
    description: ''
paths:
  /api/v1/lightning/nodes/rankings/liquidity:
    get:
      description: ''
      meta:
        element: ''
        originalPath: https://mempool.space/api/v1/lightning/nodes/rankings/liquidity
      operationId: get-api-v1-lightning-nodes-rankings-liquidity
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/liquidityranking"
                  
components:
  schemas:
    liquidityranking:
      type: object
      additionalProperties: false
        properties:
          alias:
            type: string
          capacity:
            type: integer
          channels:
            type: integer
          city:
            anyOf:
              - additionalProperties: false
                  properties:
                    de:
                      type: string
                    en:
                      type: string
                  required: []
                  title: City
                  type: object
                  - type: 'null'
          country:
            anyOf:
              - additionalProperties: false
                  properties:
                    de:
                      type: string
                    en:
                      type: string
                  required: []
                  title: City
                  type: object
                - type: 'null'
          firstSeen:
            type: integer
          iso_code:
            anyOf:
              - type: 'null'
              - type: string
          publicKey:
            type: string
          subdivision:
            anyOf:
              - type: 'null'
              - type: string
          updatedAt:
            type: integer
        required: []
        title: APIV1LightningNodes
